### ISSUE TITLE
wrong reshape after transpose optimizer 

### ISSUE THREAD

**Issue by nbcsm** [onnx/tensorflow-onnx#226]
**yaml for repro:**
```
resnet50_v1:
  model_type: saved_model
  url: http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v1_fp32_savedmodel_NHWC.tar.gz
  model: resnet_v1_fp32_savedmodel_NHWC/1538686669
  input_get: get_beach
  inputs:
    "input_tensor:0": [64, 224, 224, 3]
  outputs:
    - ArgMax:0
    - softmax_tensor:0
#    - resnet_model/final_reduce_mean:0
```

**error message:**
        run_onnx FAIL [ONNXRuntimeError] : 1 : GENERAL ERROR : [ShapeInferenceError] Incompatible dimensions for matrix multiplication
=== RESULT: 1 failed of 1, backend=onnxruntime

**root cause**
![image](https://user-images.githubusercontent.com/32868157/49738250-e414e200-fcc9-11e8-89fa-271b69d6a2d0.png)

shape attribute in reshape node is wrong, (64, 1, 1, 2048) is expected.
it is added by post_optimize_action in transpose optimizer, which decides the shape value based on input node shape.
the problem is when a transpose is moved over a node, the node SHAPE needs to be backward transposed as well.
